### PR TITLE
Change Codes for :home and :end; add Codes for :find and :select.

### LINKED ISSUE #1: Codes.keys :home and :end aren't correct on my platform.
While working on building some neat stuff with your libraries, I noticed that `Code.keys[:home]` and `Codes.keys[:end]` are not correct/working for my platform.

You currently have them as: https://github.com/piotrmurach/tty-reader/blob/aa2213d4ac16a26cadba53417d44e741d6d4b190/lib/tty/reader/codes.rb#L47-L52

But on my keyboard, on my 64-bit Linux distro, they are actually:
```ruby
home:      "\e[H",
insert:    "\e[2~",
delete:    "\e[3~",
end:       "\e[F",
page_up:   "\e[5~",
page_down: "\e[6~",
```

I'm not sure how to resolve this, because I'm sure your codes worked for you, but they don't work for me.

### PR DESCRIPTION
**Pull request by jemc**
Resolves #1.

### CODE REVIEW

**Comment by jemc** [comment]
The CI failures in Travis seem to also be present on master.

**Comment by piotrmurach** [comment]
Thanks!

**Comment by DannyBen** [comment]
Is this already merged in the published gem? If so, it still does not solve Home and End keys for me, whereas with the `rb-readline` gem it works.

This is my sample script:

```ruby
require 'tty-reader'
require 'readline'

puts "tty-reader"
reader = TTY::Reader.new
p "Received: " + reader.read_line

puts "----"

puts "rb-readline"
p "Recevied: " + Readline::readline
```

This is how it looks (pressing home and end simply does nothing, and the string stores some escape codes)

anim

This is the output (pasted here for reference):

```
tty-reader
home and end
"Received: home\e[1~ and end\e[1~\n"
----
rb-readline
home
"Recevied: home"
```

**Comment by piotrmurach** [comment]
Hi Danny,

Thank you for providing this detailed example. Would you mind submitting a patch to add to the examples folder? Would you mind also opening a new issue? Unfortunately, `tty-reader` is not as powerful as `rb-readline` (not yet 😄 ) 

I've merged this originally but was never really convinced by how `tty-reader` solves the issue of `home` and `end` keys. That is why I haven't released anything since the first release. 

I have recently started rewriting how recognition of keys works due to many reasons but the most important one being the fact that `home` key is represented differently on different terminal emulators. For example, `\e[7~` on `xrvt` and on mac `\eOH` and quite few other. Therefore, I needed to change lookup table. The changes don't work yet but soon I should be in position to release new version. However, I need to do thorough testing to ensure that `tty-prompt`, the library it was extracted from works as expected.

**Pull request merged**
